/*
 * data.js — every number and sentence the wall shows, with where it comes from.
 *
 * Baked, not queried live, so the hallway screen never breaks when Spark, Polaris or
 * the NFS mount restarts. Per-loop samples (the clip, twin, rollout and Cosmos window
 * on screen) come from assets/clips/manifest.json and assets/media/media.js, both
 * generated by the build scripts (see README). When a number changes, change it here
 * and in its source doc together.
 *
 * Vocabulary follows ../TERMINOLOGY.md: proving ground, driving policy, actors,
 * serving mode, rollout triage.
 */
window.WALL_DATA = {
  snapshot: "2026-10-06",

  brand: {
    name: "<b>EAD</b>-Data Lakehouse",
    sub: "Autonomous-driving proving ground",
    sub_ko: "자율주행 검증장",
    loop: "Real drives → hard cases → digital twins → closed-loop verdicts",
  },

  // Seconds each chapter stays on screen (≈ 75 s per loop).
  durations: { collect: 11, curate: 12, serve: 13, reconstruct: 13, validate: 14, triage: 12 },

  chapters: [
    {
      id: "collect", idx: "01", title: "Collect", ko: "수집",
      rail: { value: "306,152", unit: "clips" },
      headline: "Real drives, every sensor",
      lede: "NVIDIA PhysicalAI-AV: 20-second drives from 25 countries, registered in our Iceberg lakehouse in place, without copying the media.",
      stats: [
        // nvidia_bronze.Clip total-records (Iceberg snapshot metadata, 2026-06-22)
        { value: 306152, label: "driving clips registered (Bronze)" },
        // MEDALLION_PROGRESS.md "Current status": ~13.5 TB on-disk sample
        { value: "13.5", suffix: " TB", label: "on-disk sample of raw camera, LiDAR and radar files" },
        // sum of total-records over the 11 nvidia_bronze tables; Radar alone 11.73 B
        { value: "12.0", suffix: " B", label: "rows in Bronze, queryable in SQL" },
      ],
    },
    {
      id: "curate", idx: "02", title: "Curate", ko: "큐레이션",
      rail: { value: "3,176", unit: "Gold clips" },
      headline: "Keep the hard ten percent",
      lede: "Two validated signals, traffic conflict between actors and camera perception (darkness, low detector confidence), merge into one difficulty score. The hardest 10 % become Gold.",
      stats: [
        // MEDALLION_PROGRESS.md: Gold = 3,176 (live camera-axis cut: 3,174–3,177 by tie handling)
        { value: 3176, label: "Gold clips: validated edge cases" },
        // clip_scores, sensor_covered = true (user_data/wall_scores.json)
        { value: 31737, label: "clips scored on every signal" },
        // PAPER_EXPERIMENTS_RESULTS.md E-A (snapshot 2026-07-16): difficulty_camera OOD AUC 0.617,
        // n_ood = 200 covered clips; the refuted metadata composite: 0.450 (VALIDITY_BATTERY_FINDINGS.md)
        { value: "0.62", label: "AUC against human-flagged hard clips (old metadata score: 0.45)" },
      ],
      funnel: [
        // tier, label, clips, colour token
        { tier: "Bronze", label: "registered as-is", clips: 306152, color: "var(--bronze)" },
        { tier: "Silver", label: "quality-checked", clips: 305724, color: "var(--silver)" },
        { tier: "Silver", label: "on disk, every signal scored", clips: 31737, color: "var(--silver)", note: "13.5 TB" },
        { tier: "Gold", label: "hardest 10 %", clips: 3176, color: "var(--gold)" },
      ],
    },
    {
      id: "serve", idx: "03", title: "Serve", ko: "진열",
      rail: { value: "189,638", unit: "episodes" },
      headline: "Served the way each validator reads",
      lede: "Gold is cut into episodes and materialised per serving mode: decision windows for open-loop scoring, NuRec scenes for closed-loop simulation, Cosmos-Transfer weather variants to stress camera perception.",
      stats: [
        // nvidia_gold.episode total-records (rebuilt 2026-10-06 with our twins; evaluation/EPISODES.md)
        { value: 189638, label: "episodes in nvidia_gold.episode" },
        // nvidia_gold.scenario (2026-10-06): 20 classes incl. our NuRec and HUGS twins (evaluation/EPISODES.md)
        { value: 20, label: "scenario classes" },
        // evaluation/materialize.py: openloop, nurec, ncore, hugsim
        { value: 4, label: "serving modes: open-loop · NuRec · NCore v4 · HUGSIM" },
      ],
      // nvidia_gold.scenario, rows = recording condition, columns = serving mode
      scenario_grid: {
        cols: ["Open-loop windows", "NuRec scenes", "Cosmos windows"],
        rows: [
          { cond: "Day", cells: [101382, 775, 21] },
          { cond: "Dawn / dusk", cells: [46722, 502, 5] },
          { cond: "Night", cells: [39108, 369, 24] },
          { cond: "Not in clip index", cells: [0, 718, 0] },
        ],
        totals: [187212, 2364, 50],
      },
      // cosmos_augmentation/gate_report.json: 43 keep / 2 hallucination / 5 not harder
      gate: { kept: 43, of: 50 },
    },
    {
      id: "reconstruct", idx: "04", title: "Reconstruct", ko: "재구성",
      rail: { value: "9", unit: "digital twins" },
      headline: "One real clip in, a drivable twin out",
      lede: "Cameras and LiDAR go to NCore, get road and object labels, and NVIDIA's neural reconstruction (NuRec) fits an OpenUSD scene that a simulator can render from any viewpoint.",
      stats: [
        // evaluation/nurec/README.md fidelity table (n = 9)
        { value: 9, label: "twins built end to end, here" },
        { value: "~6", suffix: " h", label: "per clip on one A10 GPU" },
        { value: "27.5–32.6", suffix: " dB", label: "PSNR against the real camera" },
      ],
      steps: [
        // twin_pipeline.sh steps, minutes from <short>.twin.json
        { key: "convert_min", label: "NCore conversion" },
        { key: "aux_min", label: "road & object labels" },
        { key: "train_min", label: "NuRec training" },
        { key: "ground_min", label: "ground mesh" },
        { key: "bundle_min", label: "AlpaSim bundle" },
      ],
    },
    {
      id: "validate", idx: "05", title: "Validate", ko: "검증",
      rail: { value: "7 / 9", unit: "outcomes agree" },
      headline: "Drive a policy inside the twin",
      lede: "The driving policy under test (VaVAM) sees only rendered cameras and steers; AlpaSim scores collisions, off-road and progress. Same clip, same policy: our twin vs NVIDIA's own reconstruction.",
      stats: [
        // evaluation/nurec/README.md result + sensitivity table
        { value: "9 / 9", label: "constant-velocity outcomes match NVIDIA's scenes" },
        { value: "7 / 9", label: "VaVAM outcomes match; a JPEG→PNG change on NVIDIA's own scene also gives 7 / 9" },
        // evaluation/ALPASIM.md batch 3: VaVAM, n = 80 NuRec scenes
        { value: "62.5", suffix: " %", label: "of 80 scenes end in a collision or off-road" },
      ],
      // evaluation/nurec/README.md, the three misses and the cross-simulator check
      notes: {
        bb4394e7: "The miss here also flips on NVIDIA's own scene when JPEG frames become PNG: VaVAM's run-to-run noise, not the twin.",
        abd45a30: "Both collide at 3.5 s; ours is classed lateral (at fault), NVIDIA's rear. VaVAM flips this one on NVIDIA's own scene too.",
        ba91fe2c: "The one twin-specific miss: on NVIDIA's scene VaVAM crosses a lane boundary after the light turns green.",
        ac73935a: "Cross-check: HUGSIM, a second simulator with no HD map, puts VaVAM's failure on the same bend (37–38 m vs 37.6–42.7 m).",
      },
    },
    {
      id: "triage", idx: "06", title: "Triage", ko: "선별",
      rail: { value: "66 %", unit: "at ½ budget" },
      headline: "Spend GPU time where failures are",
      lede: "An open-loop screen ranks which clips earn a 38-second closed-loop rollout: the policy's own open-loop pass, read against five reference policies. The budget is a dial.",
      stats: [
        // evaluation/SKIP.md: ladder-only screen, n = 80, at-fault target
        { value: "66", suffix: " %", label: "of at-fault failures found with half the rollouts (random: 50 %)" },
        // nvidia_ingestion/STORAGE_SIZING.md, validation cost: 16.8 of 33.5 GPU-h when the open-loop pass is run anyway
        { value: "~17", suffix: " GPU-h", label: "saved per policy per Gold re-curation, open-loop pass already run" },
        // evaluation/SKIP.md (2026-10-06): VaVAM's own open-loop pass 11.6 s/clip on one GPU; rollout ~38 s
        { value: "12 s vs 38 s", label: "open-loop screen vs closed-loop rollout, per clip" },
      ],
      budget: 0.5,
      // fallback when media.js has no triage block (SKIP.md table, screen row)
      curve: [[0, 0], [0.1, 0.098], [0.2, 0.268], [0.3, 0.341], [0.4, 0.512], [0.5, 0.659], [0.6, 0.732], [0.8, 0.902], [1, 1]],
    },
  ],

  footer: [
    "Iceberg · Polaris · MinIO · Spark",
    "NCore · NuRec · AlpaSim · HUGSIM · Cosmos",
    "A10 · RTX 6000 · DGX Spark",
  ],
};
