apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kang-pvc
  namespace: name-twin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem