apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc
  namespace: name-twin
spec:
  storageClassName: ceph-block  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Ti